import "./global.css";

// import { type ReactNode } from "react";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pomodoro Next",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
  robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

// export default function RootLayout({ children }: { children: ReactNode }) {
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <noscript>You need to enable JavaScript to run this app.</noscript>
        {children}
      </body>
    </html>
  );
}
