name: storybook - Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write
  pages: write

env:
  NODE_VERSION: 18.x
  PNPM_VERSION: 8
  STORYBOOK_BUILD_PATH: storybook-static
  STORYBOOK_DOCS_BRANCH: docs/storybook
  TEMP_DIR: tmp
  GH_PAGES_STORYBOOK_SUBDIR: storybook

jobs:
  storybook_deploy:
    name: Build and Deploy Storybook into gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: checkout current branch
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Storybook
        run: pnpm storybook-build

      - uses: actions/upload-pages-artifact@v2
        name: Upload Pages Artifact
        with:
          name: Storybook
          path: ${{ env.STORYBOOK_BUILD_PATH }}

      - name: Deploy to ${{ env.STORYBOOK_DOCS_BRANCH }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.STORYBOOK_BUILD_PATH }}
          publish_branch: ${{ env.STORYBOOK_DOCS_BRANCH }}

      - name: create dir for gh-pages
        run: |
          mkdir -p ${TEMP_DIR}
          mv ${STORYBOOK_BUILD_PATH} ${TEMP_DIR}/${GH_PAGES_STORYBOOK_SUBDIR}

      - uses: actions/upload-pages-artifact@v2
        name: Upload Pages Artifact
        with:
          name: Github Pages
          path: ${{ env.TEMP_DIR }}

      - uses: actions/deploy-pages@v2
        id: deployment
        with:
          artifact_name: Github Pages
