name: storycap - Generate and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  NODE_VERSION: 18.x
  PNPM_VERSION: 8
  STORYCAP_PATH: __screenshots__
  STORYCAP_DOCS_BRANCH: docs/storycap

jobs:
  storybook_deploy:
    name: Generate and Deploy latest storycap
    runs-on: ubuntu-latest

    steps:
      - name: checkout current branch
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Storybook
        run: pnpm vrt:capture

      - name: Deploy to ${{ env.STORYCAP_DOCS_BRANCH }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.STORYCAP_PATH }}
          publish_branch: ${{ env.STORYCAP_DOCS_BRANCH }}
